import type { SupportedLanguage } from "~/types/session.ts";

export interface LanguageInfo {
  code: SupportedLanguage;
  label: string;
  bcp47: string;
  flag: string;
}

export const LANGUAGES: Record<SupportedLanguage, LanguageInfo> = {
  en: { code: "en", label: "English", bcp47: "en-US", flag: "🇬🇧" },
  de: { code: "de", label: "Deutsch", bcp47: "de-DE", flag: "🇩🇪" },
  fr: { code: "fr", label: "Français", bcp47: "fr-FR", flag: "🇫🇷" },
  it: { code: "it", label: "Italiano", bcp47: "it-IT", flag: "🇮🇹" },
  es: { code: "es", label: "Español", bcp47: "es-ES", flag: "🇪🇸" },
  pt: { code: "pt", label: "Português", bcp47: "pt-PT", flag: "🇵🇹" },
  ms: { code: "ms", label: "Bahasa Melayu", bcp47: "ms-MY", flag: "🇲🇾" },
  cs: { code: "cs", label: "Čeština", bcp47: "cs-CZ", flag: "🇨🇿" },
  sk: { code: "sk", label: "Slovenčina", bcp47: "sk-SK", flag: "🇸🇰" },
  ar: { code: "ar", label: "العربية", bcp47: "ar-SA", flag: "🇸🇦" },
  bg: { code: "bg", label: "Български", bcp47: "bg-BG", flag: "🇧🇬" },
  ca: { code: "ca", label: "Català", bcp47: "ca-ES", flag: "🏳️" },
  da: { code: "da", label: "Dansk", bcp47: "da-DK", flag: "🇩🇰" },
  el: { code: "el", label: "Ελληνικά", bcp47: "el-GR", flag: "🇬🇷" },
  et: { code: "et", label: "Eesti", bcp47: "et-EE", flag: "🇪🇪" },
  fi: { code: "fi", label: "Suomi", bcp47: "fi-FI", flag: "🇫🇮" },
  he: { code: "he", label: "עברית", bcp47: "he-IL", flag: "🇮🇱" },
  hi: { code: "hi", label: "हिन्दी", bcp47: "hi-IN", flag: "🇮🇳" },
  hr: { code: "hr", label: "Hrvatski", bcp47: "hr-HR", flag: "🇭🇷" },
  hu: { code: "hu", label: "Magyar", bcp47: "hu-HU", flag: "🇭🇺" },
  id: { code: "id", label: "Bahasa Indonesia", bcp47: "id-ID", flag: "🇮🇩" },
  ja: { code: "ja", label: "日本語", bcp47: "ja-JP", flag: "🇯🇵" },
  ko: { code: "ko", label: "한국어", bcp47: "ko-KR", flag: "🇰🇷" },
  lt: { code: "lt", label: "Lietuvių", bcp47: "lt-LT", flag: "🇱🇹" },
  lv: { code: "lv", label: "Latviešu", bcp47: "lv-LV", flag: "🇱🇻" },
  nl: { code: "nl", label: "Nederlands", bcp47: "nl-NL", flag: "🇳🇱" },
  no: { code: "no", label: "Norsk", bcp47: "nb-NO", flag: "🇳🇴" },
  pl: { code: "pl", label: "Polski", bcp47: "pl-PL", flag: "🇵🇱" },
  ro: { code: "ro", label: "Română", bcp47: "ro-RO", flag: "🇷🇴" },
  ru: { code: "ru", label: "Русский", bcp47: "ru-RU", flag: "🇷🇺" },
  sl: { code: "sl", label: "Slovenščina", bcp47: "sl-SI", flag: "🇸🇮" },
  sr: { code: "sr", label: "Српски", bcp47: "sr-RS", flag: "🇷🇸" },
  sv: { code: "sv", label: "Svenska", bcp47: "sv-SE", flag: "🇸🇪" },
  th: { code: "th", label: "ไทย", bcp47: "th-TH", flag: "🇹🇭" },
  tr: { code: "tr", label: "Türkçe", bcp47: "tr-TR", flag: "🇹🇷" },
  uk: { code: "uk", label: "Українська", bcp47: "uk-UA", flag: "🇺🇦" },
  vi: { code: "vi", label: "Tiếng Việt", bcp47: "vi-VN", flag: "🇻🇳" },
  zh: { code: "zh", label: "中文", bcp47: "zh-CN", flag: "🇨🇳" },
};

export const LANGUAGE_LIST = Object.values(LANGUAGES);

export const LANG_NAMES: Record<SupportedLanguage, string> = {
  en: "English",
  de: "German",
  fr: "French",
  it: "Italian",
  es: "Spanish",
  pt: "Portuguese",
  ms: "Malay",
  cs: "Czech",
  sk: "Slovak",
  ar: "Arabic",
  bg: "Bulgarian",
  ca: "Catalan",
  da: "Danish",
  el: "Greek",
  et: "Estonian",
  fi: "Finnish",
  he: "Hebrew",
  hi: "Hindi",
  hr: "Croatian",
  hu: "Hungarian",
  id: "Indonesian",
  ja: "Japanese",
  ko: "Korean",
  lt: "Lithuanian",
  lv: "Latvian",
  nl: "Dutch",
  no: "Norwegian",
  pl: "Polish",
  ro: "Romanian",
  ru: "Russian",
  sl: "Slovenian",
  sr: "Serbian",
  sv: "Swedish",
  th: "Thai",
  tr: "Turkish",
  uk: "Ukrainian",
  vi: "Vietnamese",
  zh: "Chinese",
};
